@startuml Package

hide private members

namespace Cpp {
    namespace Package {
        ' *************** ALGORITHMS ***************
        class CMakeGenerator {
            +string generate(Class in)
        }

        class Translator
        {
            +visit(PlantUml.Variable v)     : bool
            +visit(PlantUml.Method m)       : bool
            +visit(PlantUml.Relationship r) : bool
            +visit(PlantUml.Container c)    : bool
            +visit(PlantUml.Element e)      : bool
            +visit(PlantUml.Note n)         : bool
            +visit(PlantUml.Separator s)    : bool
            +visit(PlantUml.Enumerator e)   : bool
            +visit(PlantUml.Parameter p)    : bool
            +visit(PlantUml.End e)          : bool
            +visit(PlantUml.Type t)         : bool

            +results() : vector<Package>
        }
        Translator .|> PlantUml.AbstractVisitor
        Translator -left-> CMakeGenerator


        class PackageGenerator implements Main.Generator {
            +generate(PlantUml.SyntaxNode root) : vector<File>
        }
        PackageGenerator *-- Translator
        PackageGenerator *-- CMakeGenerator

        class Package
        {
            +name  : string
            +files : vector<path>
        }
        Package *-- Package
    }
}
@enduml